# Rule N005: Limit method name length to <= 32 characters
# Reference: https://github.com/mathworks/MATLAB-Coding-Guidelines/blob/main/MATLAB-Coding-Guidelines.md#functions

[rule]
id = "MW-N005"
name = "method-name-length"
description = "Method name exceeds 32 characters"
severity = "warning"
enabled = true

[query]
# Match method definitions within classes
pattern = """
(methods
  (function_definition
    name: (identifier) @method_name
  )
)
"""

[message]
template = "Method '{method_name}' exceeds recommended 32 character limit"

[metadata]
reference = "https://github.com/mathworks/MATLAB-Coding-Guidelines/blob/main/MATLAB-Coding-Guidelines.md#functions"
guideline = "naming.method.maxLength"
motivation = "Understandability - shorter names facilitate code review"
