# Rule N003: Limit function name length to <= 32 characters
# Reference: https://github.com/mathworks/MATLAB-Coding-Guidelines/blob/main/MATLAB-Coding-Guidelines.md#functions

[rule]
id = "MW-N003"
name = "function-name-length"
description = "Function name exceeds 32 characters"
severity = "warning"
enabled = true

[query]
# Match function definitions with long names
pattern = """
(function_definition
  name: (identifier) @function_name
) @function
"""

[message]
template = "Function '{function_name}' exceeds recommended 32 character limit"

[metadata]
reference = "https://github.com/mathworks/MATLAB-Coding-Guidelines/blob/main/MATLAB-Coding-Guidelines.md#functions"
guideline = "naming.function.maxLength"
motivation = "Understandability - shorter names facilitate code review"
